### PR TITLE
Add Discord information and corrected name

### PR DESCRIPTION
**Pull request by immewnity**
Discord information per comments in #344

### CODE REVIEW

**Comment by tommeagher** [comment]
This looks great, Matthew. Thank you! We'll go ahead and merge this into develop. We appreciate your contributions.

**Comment by tommeagher** [comment]
Hey Matthew, we hadn't had a chance to merge this yet but full intend to. Did you mean to close it? Can you reopen so we can merge?

**Comment by immewnity** [comment]
I've never felt more tech illiterate than with GitHub 😂 Was cleaning up my branches and totally forgot about this. Reopened for merging :)

**Comment by tommeagher** [comment]
This is great. Thanks, again!

**Pull request merged**
