### PR TITLE
Improves expired session handling

### PR DESCRIPTION
**Pull request by bobweston**
Creates a page for expired tokens and modifies controllers to allow users to be redirected to it.

The expired_token view notifies user about the expired login/invitation and provides a form with his/her email address prepopulated to allow them to resubmit.

This addresses issue #111 

Please note for credit that I paired with @myersjustinc on this work.

### CODE REVIEW

**Comment by tommeagher** [comment]
@bobweston, you're on 🔥 ! We'll take a look at this on Monday and holler if we have any questions for you. Thank you so much!

**Comment by GabeIsman** [comment]
@bobweston Thanks for implementing this! I've just added a few minor tweaks, but I think there are a few more things we should address before merging.

1. I think this functionality should live in `sessions_controller` not `static_controller`. I think `unknown_user` should probably be there too, even though it is static. This will also remove the need to make exceptions to the authorization policy in `static_controller`.

2. I wonder if we could turn the login form into a partial that could be shared between `expired` and `login`. Alternatively, perhaps we could make the login page more flexible, so that you could pass it an email to pre-fill and a message to display. I'm not thrilled with the repetition between the two views as it stands.

3. While this certainly makes the experience of clicking on an expired link much nicer, I'm not sure that it actually solves the issue in #111, which is that the invitation experience is bad. You certainly don't have to address that in this PR, but if you wanted to, I think adding an option to adjust the expiration window to `LoginToken#create`, and maybe even encoding in the JWT payload `type: 'invitation'` somehow, would allow us to make the invitation experience more friendly. Again, you definitely don't need to address this in this PR.

Thanks to both of you @bobweston and @myersjustinc! This is awesome work.

**Comment by bobweston** [comment]
hi @GabeIsman Thanks for the feedback. My enthusiasm got the best of me and I can see I should have created a partial. Sorry about that. I'll try to knock these changes out asap. Again, apologies for if this was a little underdone. :)

We're getting a lof of usage from the app and I'm just excited about contributing.

**Comment by GabeIsman** [comment]
@bobweston No need to apologize! I'm thrilled that you're excited about contributing. And that Klaxon is seeing so much usage. It's fantastic!

**Comment by bobweston** [comment]
hi @GabeIsman I've addressed items 1 and 2 in your list here. Could we create a ticket for item three to discuss. We can try to add that work later. I'll admit I'm not quite clear on how those changes would work. So would love to pick your brain a bit about it.

**Comment by myersjustinc** [comment]
@GabeIsman's probably right that it could take up its own PR. There's a decent amount of `LoginToken`-related refactoring that could take place there, and it'd be nice to do that as one unit.

(Of course, if we'd all rather do that in this PR instead of the current patchier approach that's here, that's fine, too. The current `LoginToken` changes are the part I was working on, so I'm happy to think on it some more if need be.)

**Comment by GabeIsman** [comment]
@bobweston @myersjustinc Definitely agree, let's table the invitation-specific improvements for follow-up work. 

Thanks you both for you work on this! It's looking great. Merging now.

**Pull request merged**
