### PR TITLE
TLDR (Issue #42 - Improve the Documentation)

### PR DESCRIPTION
**Pull request by jacksongs**
Hi all,

Love the project, hoping to help out where I can. Here's a crack at a TLDR to top the Readme, discussed in issue #42 .

### CODE REVIEW

**Comment by tommeagher** [comment]
Thanks, @jacksongs. This is great. We've merged this into our docs branch for our next release updating the documentation. We'd like to add you to our list of contributors. What name should we use? 
And are you using Klaxon in your newsroom? If so, what news organization do you work for?

**Comment by jacksongs** [comment]
Hi Tom,

I'm Jackson Gothe-Snape, journalist for SBS News in Australia. Very happy to be able to contribute.

I am running a Klaxon instance for testing and my own alerts and I hope to offer it to colleagues once it's stable.

I have more experience in python/django than ruby/rails, but I'll try to tackle some issues where I can.

**Comment by tommeagher** [comment]
Jackson, awesome. We'll add you to our contributors list. If you have any feedback or insight from your use, we'd love to hear it, either as an issue or through our Google Group. Thanks for your help with this!

**Comment by jacksongs** [comment]
No worries, if you could also add "SBS News" alongside my name to the
contributors list my boss would love it. Thanks again.

**Comment by tommeagher** [comment]
I added your affiliation, @jacksongs.

This PR is subsumed and closed by #95.

**Pull request closed without merging**
