### PR TITLE
reliably sort pages in watching

### PR DESCRIPTION
**Pull request by jeremybmerrill**
Hey y'all... Another PR from me!

A ton of folks have picked up Klaxon this week, so the number of pages that we're "watching" is increasing. I noticed that when a new site was watched, where it showed up in the list wasn't predictable. Klaxon doesn't appear to sort them at all, so I made this little tweak to sort them oldest first.

### CODE REVIEW

**Comment by ivarvong** [comment]
@jeremybmerrill That's exciting! Thanks for the PR – definitely makes sense to provide a stable sort order. Do we want to move this into a scope?

**Comment by tommeagher** [comment]
Thanks, Jeremy! This is a great idea and I'm glad you raise the issue. I wonder if the initial sorting should be by the name of the item or the site, if multiple reporters are adding watched pages over time, they may not know when something is added.

We could then allow a user to re-sort the table based on created, name or site. Just a thought.

**Comment by jeremybmerrill** [comment]
All of those sound like good solutions too, Tom. 

At least in our case, multiple people are often adding the same sites (e.g. the ODNI website for the release of that report yesterday). I'm not sure if their naming decisions will be consistent enough to allow the second user to find the first user's alert (e.g. one person could write "ODNI", another "DNI", another "Intelligence Report", another "Jeremy's alert for ODNI report"). But sorting by the URL might work well.

And with regard to chron, I initially proposed normal chron, but I now think reverse chron would work better (so regardless of the name, the ODNI alert would appear at the top, since people only cared yesterday).

In any case, I obviously defer to y'all, with a more complete view of how this is being used. I think it's important to have a consistent sort, but all of these possibilities would work well for that. 

Thanks again!

(Incidentally, Klaxon seems to be missing certain page updates for minutes or hours after they occur. It was 30 minutes late to the ODNI report, and about 12 hours late to another page update yesterday. Is this a familiar bug? I haven't yet dug into the logs to see what could be going on; could easily be a problem on my end.)

**Comment by GabeIsman** [comment]
Updated this sorting to be reverse chronological. Captured the task of adding sorting in #82.

**Comment by jeremybmerrill** [comment]
cool, thanks all!

**Pull request merged**
